// Mocks generated by Mockito 5.4.4 from annotations
// in holo_market_place_app/test/features/products/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:holo_market_place_app/features/products/data/datasources/product/product_local_datasource.dart'
    as _i6;
import 'package:holo_market_place_app/features/products/data/datasources/product/product_remote_datasource.dart'
    as _i3;
import 'package:holo_market_place_app/features/products/data/dto/product_dto.dart'
    as _i2;
import 'package:holo_market_place_app/features/products/domain/entities/product/category.dart'
    as _i5;
import 'package:holo_market_place_app/features/products/domain/entities/product/product.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDto_0 extends _i1.SmartFake implements _i2.ProductDto {
  _FakeProductDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ProductDto>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ProductDto>>.value(<_i2.ProductDto>[]),
      ) as _i4.Future<List<_i2.ProductDto>>);

  @override
  _i4.Future<_i2.ProductDto> getProductById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ProductDto>.value(_FakeProductDto_0(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ProductDto>);

  @override
  _i4.Future<List<_i2.ProductDto>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [category],
        ),
        returnValue: _i4.Future<List<_i2.ProductDto>>.value(<_i2.ProductDto>[]),
      ) as _i4.Future<List<_i2.ProductDto>>);

  @override
  _i4.Future<List<_i5.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i4.Future<List<_i5.Category>>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i6.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.Product>> getCachedProducts() => (super.noSuchMethod(
        Invocation.method(
          #getCachedProducts,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Product>>.value(<_i7.Product>[]),
      ) as _i4.Future<List<_i7.Product>>);

  @override
  _i4.Future<void> cacheProducts(List<_i7.Product>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.Product?> getProductById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i4.Future<_i7.Product?>.value(),
      ) as _i4.Future<_i7.Product?>);

  @override
  _i4.Future<List<_i7.Product>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [category],
        ),
        returnValue: _i4.Future<List<_i7.Product>>.value(<_i7.Product>[]),
      ) as _i4.Future<List<_i7.Product>>);

  @override
  _i4.Future<List<_i5.Category>> getCachedCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCachedCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Category>>.value(<_i5.Category>[]),
      ) as _i4.Future<List<_i5.Category>>);

  @override
  _i4.Future<void> cacheCategories(List<_i5.Category>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCategories,
          [categories],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
